version: "3"

services: 
  app: 
    build: .
    # port mapping?
    ports: 
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main2:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes: 
      # Mapping --> We could also map app:app to just update files of the app (With that we are more precise in store different things)
      - ./app:/usr/src/app
      - ./models:/usr/src/models
    environment: 
      #- db_host=mysql://username:password@hostadress:3308/db_name
      # hostadress is name of service or in other cases a IP_Address
      - db_host=postgresql://postgres:postgres@postgres_db:5432/postgres'
      # is it right? Why do I need this?

    # database need to be run to run the application properly
    depends_on: 
      - postgres_db

  postgres_db: 
    image: postgres:latest
    ports: 
      - "5434:5432"
    env_file:
    - .env-local

    #environment:
    # we could also store env values in an env.file? 
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
      #POSTGRES_PASSWORD: postgres
    volumes:
      - pgdb:/var/lib/postgresql/database


volumes: 
  pgdb:
    